add environment switcher

diff --git a/zsh_aws_rds b/zsh_aws_rds
--- a/zsh_aws_rds
+++ b/zsh_aws_rds
@@ -19,6 +19,36 @@ function dball() {
   dbaua $1
 }
 
+## switch env
+argp () {
+	if [[ -z "$1" ]]
+	then
+		# unset AWS_DEFAULT_PROFILE AWS_PROFILE AWS_EB_PROFILE
+		# echo AWS profile cleared.
+    echo $_ARGUS_PROFILE
+		return
+	fi
+	# local -a available_profiles
+	# available_profiles=($(aws_profiles))
+	# if [[ -z "${available_profiles[(r)$1]}" ]]
+	# then
+	# 	echo "${fg[red]}Profile '$1' not found in '${AWS_CONFIG_FILE:-$HOME/.aws/config}'" >&2
+	# 	echo "Available profiles: ${(j:, :)available_profiles:-no profiles found}${reset_color}" >&2
+	# 	return 1
+	# fi
+  _setArgusProfile $1
+}
+
+_setArgusProfile() {
+  local argus_profile
+  case $1 in
+    d) argus_profile="development" ;;
+    s) argus_profile="staging" ;;
+    p) argus_profile="production" ;;
+  esac
+
+  export _ARGUS_PROFILE=$argus_profile
+}
 
 # users db
 
